language: android
env:
    global:
        - ADB_INSTALL_TIMEOUT=15
android:
    components:
        - build-tools-21.1.2
        - extra-android-support
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-21
before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
    - echo Hello
    - ./gradlew clean test connectedCheck
addons:
    apt:
        packages:
        - ncftp
        - tree
